---

# Example Badgr Server sandbox configuration
# for single server community
# installs

- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    EDXAPP_LMS_NGINX_PORT: '80'
    edx_platform_version: 'master'
    # Set to false if deployed behind another proxy/load balancer.
    NGINX_SET_X_FORWARDED_HEADERS: True
    # These should stay false for the public AMI
    COMMON_ENABLE_DATADOG: False
    SANDBOX_ENABLE_ECOMMERCE: False
    COMMON_ENABLE_SPLUNKFORWARDER: False
  roles:
    - role: nginx
      nginx_sites:
      - badgr_server
    - role: nginx
    - role: badgr_server
    - badgr_server
